### ISSUE TITLE
500 error when removing a user

### ISSUE THREAD

**Issue by haruka-7** [pluxml/PluXml-Nexus#1]
When removing a user confirmModal.js return the error below.

```
Slim Application Error

The application could not run because of the following error:
Details
Type: TypeError
Code: 0
Message: Return value of Slim\Handlers\Strategies\RequestResponse::__invoke() must implement interface Psr\Http\Message\ResponseInterface, null returned
File: /web/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php
Line: 43
Trace

#0 /web/vendor/slim/slim/Slim/Routing/Route.php(381): Slim\Handlers\Strategies\RequestResponse->__invoke(Array, Object(Slim\Psr7\Request), Object(Slim\Psr7\Response), Array)
#1 /web/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Slim\Routing\Route->handle(Object(Slim\Psr7\Request))
#2 /web/app/Middlewares/BackofficeMiddleware.php(23): Slim\MiddlewareDispatcher->handle(Object(Slim\Psr7\Request))
#3 /web/vendor/slim/slim/Slim/MiddlewareDispatcher.php(283): App\Middlewares\BackofficeMiddleware->__invoke(Object(Slim\Psr7\Request), Object(Slim\MiddlewareDispatcher))
#4 /web/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): class@anonymous->handle(Object(Slim\Psr7\Request))
#5 /web/vendor/slim/slim/Slim/Routing/Route.php(341): Slim\MiddlewareDispatcher->handle(Object(Slim\Psr7\Request))
#6 /web/vendor/slim/slim/Slim/Routing/RouteRunner.php(84): Slim\Routing\Route->run(Object(Slim\Psr7\Request))
#7 /web/app/Middlewares/FormOldValuesMiddleware.php(28): Slim\Routing\RouteRunner->handle(Object(Slim\Psr7\Request))
#8 /web/vendor/slim/slim/Slim/MiddlewareDispatcher.php(283): App\Middlewares\FormOldValuesMiddleware->__invoke(Object(Slim\Psr7\Request), Object(Slim\Routing\RouteRunner))
#9 /web/app/Middlewares/IsLoggedMiddleware.php(25): class@anonymous->handle(Object(Slim\Psr7\Request))
#10 /web/vendor/slim/slim/Slim/MiddlewareDispatcher.php(283): App\Middlewares\IsLoggedMiddleware->__invoke(Object(Slim\Psr7\Request), Object(class@anonymous))
#11 /web/app/Middlewares/RouterViewMiddleware.php(26): class@anonymous->handle(Object(Slim\Psr7\Request))
#12 /web/vendor/slim/slim/Slim/MiddlewareDispatcher.php(283): App\Middlewares\RouterViewMiddleware->__invoke(Object(Slim\Psr7\Request), Object(class@anonymous))
#13 /web/app/Middlewares/CsrfTokenMiddleware.php(29): class@anonymous->handle(Object(Slim\Psr7\Request))
#14 /web/vendor/slim/slim/Slim/MiddlewareDispatcher.php(283): App\Middlewares\CsrfTokenMiddleware->__invoke(Object(Slim\Psr7\Request), Object(class@anonymous))
#15 /web/vendor/slim/csrf/src/Guard.php(438): class@anonymous->handle(Object(Slim\Psr7\Request))
#16 /web/vendor/slim/slim/Slim/MiddlewareDispatcher.php(188): Slim\Csrf\Guard->process(Object(Slim\Psr7\Request), Object(class@anonymous))
#17 /web/vendor/slim/slim/Slim/Middleware/ErrorMiddleware.php(107): class@anonymous->handle(Object(Slim\Psr7\Request))
#18 /web/vendor/slim/slim/Slim/MiddlewareDispatcher.php(140): Slim\Middleware\ErrorMiddleware->process(Object(Slim\Psr7\Request), Object(class@anonymous))
#19 /web/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): class@anonymous->handle(Object(Slim\Psr7\Request))
#20 /web/vendor/slim/slim/Slim/App.php(215): Slim\MiddlewareDispatcher->handle(Object(Slim\Psr7\Request))
#21 /web/vendor/slim/slim/Slim/App.php(199): Slim\App->handle(Object(Slim\Psr7\Request))
#22 /web/public/index.php(34): Slim\App->run()
#23 {main}
```

**Comment by haruka-7** [comment]
Fixed.
